on: [push]
name: build
jobs:
  runhaskell:
    name: Hello World
    runs-on: ubuntu-latest # or macOS-latest, or windows-latest
    steps:
      - uses: actions/checkout@v3
      - uses: haskell/actions/setup@v2
        with:
          ghc-version: '9.4.8' # Exact version of ghc to use
          enable-stack: true
          stack-version: 'latest'
      - run: stack test
